### ISSUE TITLE
解密出来有时候不一样

### ISSUE THREAD

**Issue by GXLR** [lzj2015/openssl_1.0.1f_lzj#1]
Generated SM2 Private Key: [B3D22B4F0AD9F2ACB66D7283A05D5B0AACCA8C8B7F9945FEC3B9683C08DEDFF4]
Public Key: [0403562EE021979BB535411B020D7D3A7F5141465A5BE93BD6A512573F7E7E58DF7496A2853BC7F214FBC6B31BDB1B2A911FA9D8200239BD4ED7AC9043974D82D6]
3076022047F31B43770451C94FDD2F5F016BAB34D46DE47E98688387A70F942B5584A7DB022100C7E854433010E0E3938C8057C0CA741E0364927DFF611DF6EC9DFAE80A7992640420A6142FAD62D681AE201493560E190C41DB22DE3356A234E7A6DE5EAB6C7A0F88040D99D330557B3DFE59296AFD3076
### crypto function ok 2345tgbvfeedc\377

Generated SM2 Private Key: [8C482D53B0BD7717DEFA497FAEE625DBFC2D4D792514BB40826581D221A4C68A]
 Public Key: [045C5FC09DC642366CBB08C2F546BAC5EC8980ACD44E74BEB5ADA04BE32AEF42B29ACB0BE89AD230D630AE4B7C76ED09FC47EB7F37EB5FCA1A1D9E285A41C28246]
30770221009896CD171D7487DCD6E03068E3DCBCC766659C45F6DD550C5B65929038731F0A022100E2B8DE70B6BC02703B138F8CC04CEA35EFD4AD5F6F54B011DCE46EDB3EB5D1970420A929A1AC758D9A281B22913ED554D2BD42BE05E629A5CAE387FF80C3E4DBC2EC040DE6E6C06BF3AE817175A1ADEC25
### crypto function ok 2345tgbvfeedc\377\377

Generated SM2 Private Key: [77B2D645B639B3519EA55421C423CADF5530897FED3BAC4CE3D36952E9BFF4AD]
 Public Key: [040A71C764052F55C88D1320DB0A7FBD2773F6029630261CD286B3D0EB7ED48AC6FF1F5E98FA1897A06142668279C1EF6B469E212715ECFE29A94BCF7ABBC7B735]
307502204D4B69ACBEC2AF8993B0C29647CDCA63690F6785901237ACDA1520558A28012E02205894F4FF8EFBFD832EA188C88C5FA71A4F1523DD78D50E05BFF4BACDFC54A15D042096F6FC5339DE1A4ABD867CAF2E3469D2D7BD186C8EE6BB9679F36A565C5A0860040DCD0BA2CDC89312B0B4CB0DE5D3
### crypto function ok 2345tgbvfeedc

**Comment by lzj2015** [comment]
> Generated SM2 Private Key: [B3D22B4F0AD9F2ACB66D7283A05D5B0AACCA8C8B7F9945FEC3B9683C08DEDFF4]
> Public Key: [0403562EE021979BB535411B020D7D3A7F5141465A5BE93BD6A512573F7E7E58DF7496A2853BC7F214FBC6B31BDB1B2A911FA9D8200239BD4ED7AC9043974D82D6]
> 3076022047F31B43770451C94FDD2F5F016BAB34D46DE47E98688387A70F942B5584A7DB022100C7E854433010E0E3938C8057C0CA741E0364927DFF611DF6EC9DFAE80A7992640420A6142FAD62D681AE201493560E190C41DB22DE3356A234E7A6DE5EAB6C7A0F88040D99D330557B3DFE59296AFD3076
> 
> ### crypto function ok 2345tgbvfeedc\377
> Generated SM2 Private Key: [8C482D53B0BD7717DEFA497FAEE625DBFC2D4D792514BB40826581D221A4C68A]
> Public Key: [045C5FC09DC642366CBB08C2F546BAC5EC8980ACD44E74BEB5ADA04BE32AEF42B29ACB0BE89AD230D630AE4B7C76ED09FC47EB7F37EB5FCA1A1D9E285A41C28246]
> 30770221009896CD171D7487DCD6E03068E3DCBCC766659C45F6DD550C5B65929038731F0A022100E2B8DE70B6BC02703B138F8CC04CEA35EFD4AD5F6F54B011DCE46EDB3EB5D1970420A929A1AC758D9A281B22913ED554D2BD42BE05E629A5CAE387FF80C3E4DBC2EC040DE6E6C06BF3AE817175A1ADEC25
> 
> ### crypto function ok 2345tgbvfeedc\377\377
> Generated SM2 Private Key: [77B2D645B639B3519EA55421C423CADF5530897FED3BAC4CE3D36952E9BFF4AD]
> Public Key: [040A71C764052F55C88D1320DB0A7FBD2773F6029630261CD286B3D0EB7ED48AC6FF1F5E98FA1897A06142668279C1EF6B469E212715ECFE29A94BCF7ABBC7B735]
> 307502204D4B69ACBEC2AF8993B0C29647CDCA63690F6785901237ACDA1520558A28012E02205894F4FF8EFBFD832EA188C88C5FA71A4F1523DD78D50E05BFF4BACDFC54A15D042096F6FC5339DE1A4ABD867CAF2E3469D2D7BD186C8EE6BB9679F36A565C5A0860040DCD0BA2CDC89312B0B4CB0DE5D3
> 
> ### crypto function ok 2345tgbvfeedc

hi, thanks for you using.
you can use  memset(msg,0,msglength) to set the memory data to 0 and avoid it.
good lucky !
Thanks!
